### ISSUE TITLE
Add persistent storage

### ISSUE THREAD

**Issue by manuellazzari-cargoone** [fpischedda/unrefined#27] opened 2022-10-26 07:44 UTC
More a feature request than an issue report. Having persisted storage and permalinks seems a very needed feature to use this tool consistently.

**Comment by fpischedda** [comment] 2022-10-26 08:15
Possibly a duplicate of #10 
I will close this one, please feel free to add comments to #10 if any

**Closed as completed by fpischedda** 2022-10-26 08:15 UTC
